version: '3'

services:
  app:
    command: "ttto run"
    env_file:
      - ops/environment
    build:
      dockerfile: ops/Dockerfile
      context: .
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5433:5432'

volumes:
  database:
